language: python
python:
  - "3.8"
install:
  - pip install kindred snakemake scispacy zenodo_get
  - pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz
script:
   - MODE=test snakemake --cores 1
